sudo: true

python:
  - "3.7"

sudo: required

cache:
  pip: true
  directories:
    - $HOME/buildout-cache

addons:
  apt:
    packages:
      - expect-dev  # provides unbuffer utility
      - python-lxml  # because pip installation is slow
      - libappindicator1
      - fonts-liberation
      - chromium-browser
      - chromium-chromedriver

env:
  - VERSION="9.0" ODOO_TEST="1" ROBOT="1" DOC="1"

virtualenv:
  system_site_packages: true

before_install:
  - wget http://chromedriver.storage.googleapis.com/2.21/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip
  - sudo chmod u+x chromedriver
  - sudo mv chromedriver /usr/bin/
  - export CHROME_BIN=chromium-browser
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
  - ./travis_before_install

install: "pip install -r requirements.txt" 

script: robot Samples/test.robot

after_success:
  - bin/travis-sphinx deploy
